--
-- PostgreSQL database dump
--

\restrict kMlKi3eABjTLDVweeAcEE5GCAbYoMQL3p18glIPm7OQVxQUebbRh2fRbds80rup

-- Dumped from database version 14.22
-- Dumped by pg_dump version 14.22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_emailverificationcode; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_emailverificationcode (
    id bigint NOT NULL,
    email character varying(254) NOT NULL,
    code character varying(6) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_used boolean NOT NULL
);


--
-- Name: api_emailverificationcode_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_emailverificationcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_emailverificationcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: custom_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    phone character varying(15),
    avatar character varying(200),
    role character varying(10) NOT NULL,
    department character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    bio text NOT NULL,
    birthday date,
    gender character varying(10),
    nickname character varying(50),
    nickname_approved character varying(20),
    nickname_candidate character varying(20),
    nickname_reject_reason character varying(255) NOT NULL,
    nickname_reviewed_at timestamp with time zone,
    nickname_reviewed_by_id bigint,
    nickname_status character varying(10) NOT NULL
);


--
-- Name: custom_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_user_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: custom_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: custom_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_user_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: custom_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.custom_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.custom_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: leetcode_problem; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leetcode_problem (
    id bigint NOT NULL,
    problem_id integer NOT NULL,
    title character varying(200) NOT NULL,
    title_slug character varying(200) NOT NULL,
    difficulty character varying(10) NOT NULL,
    is_premium boolean NOT NULL,
    content text NOT NULL,
    acceptance_rate double precision NOT NULL,
    submission_count integer NOT NULL,
    accepted_count integer NOT NULL,
    tags jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: leetcode_problem_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.leetcode_problem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leetcode_problem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nickname_review_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.nickname_review_log (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    nickname_value character varying(20) NOT NULL,
    hit_rule character varying(64) NOT NULL,
    message character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    operator_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: nickname_review_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.nickname_review_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nickname_review_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: problem_completion; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.problem_completion (
    id bigint NOT NULL,
    status character varying(15) NOT NULL,
    attempts integer NOT NULL,
    last_attempted timestamp with time zone,
    completed_at timestamp with time zone,
    solution_code text NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    problem_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: problem_completion_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.problem_completion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.problem_completion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: problem_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.problem_tag (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    slug character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL
);


--
-- Name: problem_tag_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.problem_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.problem_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_activity (
    id bigint NOT NULL,
    activity_type character varying(20) NOT NULL,
    ip_address inet,
    user_agent text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    problem_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: user_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_activity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_emailverificationcode api_emailverificationcode_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_emailverificationcode
    ADD CONSTRAINT api_emailverificationcode_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: custom_user custom_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user
    ADD CONSTRAINT custom_user_email_key UNIQUE (email);


--
-- Name: custom_user_groups custom_user_groups_customuser_id_group_id_ea14f886_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user_groups
    ADD CONSTRAINT custom_user_groups_customuser_id_group_id_ea14f886_uniq UNIQUE (customuser_id, group_id);


--
-- Name: custom_user_groups custom_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user_groups
    ADD CONSTRAINT custom_user_groups_pkey PRIMARY KEY (id);


--
-- Name: custom_user custom_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user
    ADD CONSTRAINT custom_user_pkey PRIMARY KEY (id);


--
-- Name: custom_user_user_permissions custom_user_user_permiss_customuser_id_permission_f9232336_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user_user_permissions
    ADD CONSTRAINT custom_user_user_permiss_customuser_id_permission_f9232336_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: custom_user_user_permissions custom_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user_user_permissions
    ADD CONSTRAINT custom_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: custom_user custom_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user
    ADD CONSTRAINT custom_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: leetcode_problem leetcode_problem_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leetcode_problem
    ADD CONSTRAINT leetcode_problem_pkey PRIMARY KEY (id);


--
-- Name: leetcode_problem leetcode_problem_problem_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leetcode_problem
    ADD CONSTRAINT leetcode_problem_problem_id_key UNIQUE (problem_id);


--
-- Name: leetcode_problem leetcode_problem_title_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leetcode_problem
    ADD CONSTRAINT leetcode_problem_title_slug_key UNIQUE (title_slug);


--
-- Name: nickname_review_log nickname_review_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nickname_review_log
    ADD CONSTRAINT nickname_review_log_pkey PRIMARY KEY (id);


--
-- Name: problem_completion problem_completion_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_completion
    ADD CONSTRAINT problem_completion_pkey PRIMARY KEY (id);


--
-- Name: problem_completion problem_completion_user_id_problem_id_e651e689_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_completion
    ADD CONSTRAINT problem_completion_user_id_problem_id_e651e689_uniq UNIQUE (user_id, problem_id);


--
-- Name: problem_tag problem_tag_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_tag
    ADD CONSTRAINT problem_tag_name_key UNIQUE (name);


--
-- Name: problem_tag problem_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_tag
    ADD CONSTRAINT problem_tag_pkey PRIMARY KEY (id);


--
-- Name: problem_tag problem_tag_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_tag
    ADD CONSTRAINT problem_tag_slug_key UNIQUE (slug);


--
-- Name: user_activity user_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_activity
    ADD CONSTRAINT user_activity_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: custom_user_email_54654c31_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_user_email_54654c31_like ON public.custom_user USING btree (email varchar_pattern_ops);


--
-- Name: custom_user_groups_customuser_id_8e3d0338; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_user_groups_customuser_id_8e3d0338 ON public.custom_user_groups USING btree (customuser_id);


--
-- Name: custom_user_groups_group_id_02874f21; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_user_groups_group_id_02874f21 ON public.custom_user_groups USING btree (group_id);


--
-- Name: custom_user_nickname_reviewed_by_id_38f003be; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_user_nickname_reviewed_by_id_38f003be ON public.custom_user USING btree (nickname_reviewed_by_id);


--
-- Name: custom_user_user_permissions_customuser_id_ec2da4cb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_user_user_permissions_customuser_id_ec2da4cb ON public.custom_user_user_permissions USING btree (customuser_id);


--
-- Name: custom_user_user_permissions_permission_id_f82b5e3f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_user_user_permissions_permission_id_f82b5e3f ON public.custom_user_user_permissions USING btree (permission_id);


--
-- Name: custom_user_username_5f1e8aad_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX custom_user_username_5f1e8aad_like ON public.custom_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: leetcode_problem_title_slug_3ee55e82_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX leetcode_problem_title_slug_3ee55e82_like ON public.leetcode_problem USING btree (title_slug varchar_pattern_ops);


--
-- Name: nickname_re_action_c542cf_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nickname_re_action_c542cf_idx ON public.nickname_review_log USING btree (action, created_at DESC);


--
-- Name: nickname_re_user_id_2cea69_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nickname_re_user_id_2cea69_idx ON public.nickname_review_log USING btree (user_id, action, created_at DESC);


--
-- Name: nickname_review_log_operator_id_0c48ce2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nickname_review_log_operator_id_0c48ce2c ON public.nickname_review_log USING btree (operator_id);


--
-- Name: nickname_review_log_user_id_74c4fa91; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nickname_review_log_user_id_74c4fa91 ON public.nickname_review_log USING btree (user_id);


--
-- Name: problem_com_problem_415fa0_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problem_com_problem_415fa0_idx ON public.problem_completion USING btree (problem_id, status);


--
-- Name: problem_com_user_id_b8fbf3_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problem_com_user_id_b8fbf3_idx ON public.problem_completion USING btree (user_id, completed_at DESC);


--
-- Name: problem_com_user_id_f81a94_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problem_com_user_id_f81a94_idx ON public.problem_completion USING btree (user_id, status);


--
-- Name: problem_completion_problem_id_8c157683; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problem_completion_problem_id_8c157683 ON public.problem_completion USING btree (problem_id);


--
-- Name: problem_completion_user_id_eda47296; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problem_completion_user_id_eda47296 ON public.problem_completion USING btree (user_id);


--
-- Name: problem_tag_name_352d6feb_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problem_tag_name_352d6feb_like ON public.problem_tag USING btree (name varchar_pattern_ops);


--
-- Name: problem_tag_slug_66d6c311_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX problem_tag_slug_66d6c311_like ON public.problem_tag USING btree (slug varchar_pattern_ops);


--
-- Name: user_activi_activit_a70d72_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_activi_activit_a70d72_idx ON public.user_activity USING btree (activity_type, created_at DESC);


--
-- Name: user_activi_user_id_e0c66f_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_activi_user_id_e0c66f_idx ON public.user_activity USING btree (user_id, created_at DESC);


--
-- Name: user_activity_problem_id_5420fe92; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_activity_problem_id_5420fe92 ON public.user_activity USING btree (problem_id);


--
-- Name: user_activity_user_id_9d5b7120; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_activity_user_id_9d5b7120 ON public.user_activity USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_custom_user_id FOREIGN KEY (user_id) REFERENCES public.custom_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_user_groups custom_user_groups_customuser_id_8e3d0338_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user_groups
    ADD CONSTRAINT custom_user_groups_customuser_id_8e3d0338_fk_custom_user_id FOREIGN KEY (customuser_id) REFERENCES public.custom_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_user_groups custom_user_groups_group_id_02874f21_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user_groups
    ADD CONSTRAINT custom_user_groups_group_id_02874f21_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_user custom_user_nickname_reviewed_by_id_38f003be_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user
    ADD CONSTRAINT custom_user_nickname_reviewed_by_id_38f003be_fk_custom_user_id FOREIGN KEY (nickname_reviewed_by_id) REFERENCES public.custom_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_user_user_permissions custom_user_user_per_customuser_id_ec2da4cb_fk_custom_us; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user_user_permissions
    ADD CONSTRAINT custom_user_user_per_customuser_id_ec2da4cb_fk_custom_us FOREIGN KEY (customuser_id) REFERENCES public.custom_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: custom_user_user_permissions custom_user_user_per_permission_id_f82b5e3f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_user_user_permissions
    ADD CONSTRAINT custom_user_user_per_permission_id_f82b5e3f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_custom_user_id FOREIGN KEY (user_id) REFERENCES public.custom_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: nickname_review_log nickname_review_log_operator_id_0c48ce2c_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nickname_review_log
    ADD CONSTRAINT nickname_review_log_operator_id_0c48ce2c_fk_custom_user_id FOREIGN KEY (operator_id) REFERENCES public.custom_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: nickname_review_log nickname_review_log_user_id_74c4fa91_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.nickname_review_log
    ADD CONSTRAINT nickname_review_log_user_id_74c4fa91_fk_custom_user_id FOREIGN KEY (user_id) REFERENCES public.custom_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: problem_completion problem_completion_problem_id_8c157683_fk_leetcode_problem_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_completion
    ADD CONSTRAINT problem_completion_problem_id_8c157683_fk_leetcode_problem_id FOREIGN KEY (problem_id) REFERENCES public.leetcode_problem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: problem_completion problem_completion_user_id_eda47296_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problem_completion
    ADD CONSTRAINT problem_completion_user_id_eda47296_fk_custom_user_id FOREIGN KEY (user_id) REFERENCES public.custom_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_activity user_activity_problem_id_5420fe92_fk_leetcode_problem_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_activity
    ADD CONSTRAINT user_activity_problem_id_5420fe92_fk_leetcode_problem_id FOREIGN KEY (problem_id) REFERENCES public.leetcode_problem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_activity user_activity_user_id_9d5b7120_fk_custom_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_activity
    ADD CONSTRAINT user_activity_user_id_9d5b7120_fk_custom_user_id FOREIGN KEY (user_id) REFERENCES public.custom_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict kMlKi3eABjTLDVweeAcEE5GCAbYoMQL3p18glIPm7OQVxQUebbRh2fRbds80rup

