# Generated by Django 5.2.11 on 2026-02-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField(unique=True, verbose_name='题目ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目标题')),
                ('title_slug', models.SlugField(max_length=200, unique=True, verbose_name='题目slug')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], max_length=10, verbose_name='难度')),
                ('is_premium', models.BooleanField(default=False, verbose_name='是否为会员题')),
                ('content', models.TextField(blank=True, verbose_name='题目描述')),
                ('acceptance_rate', models.FloatField(default=0.0, verbose_name='通过率')),
                ('submission_count', models.IntegerField(default=0, verbose_name='提交次数')),
                ('accepted_count', models.IntegerField(default=0, verbose_name='通过次数')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LeetCode题目',
                'verbose_name_plural': 'LeetCode题目列表',
                'db_table': 'leetcode_problem',
                'ordering': ['problem_id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='标签slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目标签',
                'verbose_name_plural': '题目标签列表',
                'db_table': 'problem_tag',
                'ordering': ['name'],
            },
        ),
               # migrations.RemoveField(
        #     model_name='customuser',
        #     name='student_id',
        # ),
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='teacher_id',
        # ),

        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', '用户'), ('admin', '管理员')], default='user', max_length=10, verbose_name='用户角色'),
        ),
    ]
