# Generated by Django 5.2.11 on 2026-02-28 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_is_staff_field_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='not_started', max_length=15, verbose_name='完成状态')),
                ('attempts', models.IntegerField(default=0, verbose_name='尝试次数')),
                ('last_attempted', models.DateTimeField(blank=True, null=True, verbose_name='最后尝试时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('solution_code', models.TextField(blank=True, verbose_name='解决方案代码')),
                ('notes', models.TextField(blank=True, verbose_name='笔记')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leetcodeproblem', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '题目完成状态',
                'verbose_name_plural': '题目完成状态记录',
                'db_table': 'problem_completion',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='problem_com_user_id_f81a94_idx'), models.Index(fields=['problem', 'status'], name='problem_com_problem_415fa0_idx'), models.Index(fields=['user', '-completed_at'], name='problem_com_user_id_b8fbf3_idx')],
                'unique_together': {('user', 'problem')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '登录'), ('view_problem', '查看题目'), ('submit_solution', '提交解答'), ('complete_problem', '完成题目'), ('profile_update', '更新资料')], max_length=20, verbose_name='活动类型')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='活动时间')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.leetcodeproblem', verbose_name='相关题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户活动',
                'verbose_name_plural': '用户活动记录',
                'db_table': 'user_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='user_activi_user_id_e0c66f_idx'), models.Index(fields=['activity_type', '-created_at'], name='user_activi_activit_a70d72_idx')],
            },
        ),
    ]
