# Generated by Django 5.2.11 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emailverificationcode_remove_customuser_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[('male', 'male'), ('female', 'female'), ('other', 'other')],
                max_length=10,
                null=True,
                verbose_name='gender'
            ),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nickname'),
        ),
    ]
