# Generated by Django 5.2.11 on 2026-04-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def init_nickname_review_fields(apps, schema_editor):
    # Use SQL directly to avoid historical model state drift issues.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE custom_user
            SET nickname_status = 'approved'
            WHERE nickname_status IS NULL OR nickname_status = '';
            """
        )
        cursor.execute(
            """
            UPDATE custom_user
            SET nickname_approved = nickname
            WHERE (nickname_approved IS NULL OR nickname_approved = '')
              AND nickname IS NOT NULL
              AND nickname <> '';
            """
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_profile_fields_to_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname_approved",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="nickname_approved"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname_candidate",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="nickname_candidate"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname_reject_reason",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="nickname_reject_reason"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname_reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="nickname_reviewed_at"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_nicknames",
                to=settings.AUTH_USER_MODEL,
                verbose_name="nickname_reviewed_by",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname_status",
            field=models.CharField(
                choices=[("approved", "approved"), ("pending", "pending"), ("rejected", "rejected")],
                default="approved",
                max_length=10,
                verbose_name="nickname_status",
            ),
        ),
        migrations.CreateModel(
            name="NicknameReviewLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submit", "submit"),
                            ("approve", "approve"),
                            ("reject", "reject"),
                            ("validation_fail", "validation_fail"),
                            ("rate_limited", "rate_limited"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                ("nickname_value", models.CharField(blank=True, default="", max_length=20, verbose_name="nickname_value")),
                ("hit_rule", models.CharField(blank=True, default="", max_length=64, verbose_name="hit_rule")),
                ("message", models.CharField(blank=True, default="", max_length=255, verbose_name="message")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operated_nickname_review_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="operator",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nickname_review_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "nickname_review_log",
                "verbose_name_plural": "nickname_review_logs",
                "db_table": "nickname_review_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="nicknamereviewlog",
            index=models.Index(fields=["user", "action", "-created_at"], name="nickname_re_user_id_2cea69_idx"),
        ),
        migrations.AddIndex(
            model_name="nicknamereviewlog",
            index=models.Index(fields=["action", "-created_at"], name="nickname_re_action_c542cf_idx"),
        ),
        migrations.RunPython(init_nickname_review_fields, noop_reverse),
    ]
