# Generated by Django 5.2.11 on 2026-05-29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_nickname_review_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("description", models.TextField(blank=True, default="", verbose_name="description")),
                ("start_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="start_at")),
                ("due_at", models.DateTimeField(verbose_name="due_at")),
                ("is_published", models.BooleanField(default=False, verbose_name="is_published")),
                ("allow_late_submission", models.BooleanField(default=False, verbose_name="allow_late_submission")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_homeworks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created_by",
                    ),
                ),
            ],
            options={
                "verbose_name": "homework_assignment",
                "verbose_name_plural": "homework_assignments",
                "db_table": "homework_assignment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomeworkProblem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                ("points", models.PositiveIntegerField(default=100, verbose_name="points")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_problems",
                        to="api.homeworkassignment",
                        verbose_name="assignment",
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_links",
                        to="api.leetcodeproblem",
                        verbose_name="problem",
                    ),
                ),
            ],
            options={
                "verbose_name": "homework_problem",
                "verbose_name_plural": "homework_problems",
                "db_table": "homework_problem",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeworkSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "not_started"),
                            ("in_progress", "in_progress"),
                            ("submitted", "submitted"),
                            ("late_submitted", "late_submitted"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="", verbose_name="notes")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="submitted_at")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created_at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated_at")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="api.homeworkassignment",
                        verbose_name="assignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "homework_submission",
                "verbose_name_plural": "homework_submissions",
                "db_table": "homework_submission",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="homeworkassignment",
            index=models.Index(fields=["is_published", "due_at"], name="homework_as_is_publ_50f7dd_idx"),
        ),
        migrations.AddIndex(
            model_name="homeworkassignment",
            index=models.Index(fields=["start_at", "due_at"], name="homework_as_start_a_124f7d_idx"),
        ),
        migrations.AddConstraint(
            model_name="homeworkproblem",
            constraint=models.UniqueConstraint(fields=("assignment", "problem"), name="uq_homework_problem_assignment_problem"),
        ),
        migrations.AddIndex(
            model_name="homeworkproblem",
            index=models.Index(fields=["assignment", "order"], name="homework_pr_assignm_1541f7_idx"),
        ),
        migrations.AddConstraint(
            model_name="homeworksubmission",
            constraint=models.UniqueConstraint(fields=("assignment", "user"), name="uq_homework_submission_assignment_user"),
        ),
        migrations.AddIndex(
            model_name="homeworksubmission",
            index=models.Index(fields=["user", "status"], name="homework_su_user_id_376c5f_idx"),
        ),
        migrations.AddIndex(
            model_name="homeworksubmission",
            index=models.Index(fields=["assignment", "status"], name="homework_su_assignm_445795_idx"),
        ),
    ]
